name: Sync Obsidian to Jekyll

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install obsidian-export
        run: pip install obsidian-export

      - name: Export Obsidian notes
        run: |
          obsidian-export vault/ _posts/

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update notes"
          git push
